wandb: ERROR Project mlops-zoomcamp-wandb/jgammerman does not contain artifact: "NYC-Taxi:v0"
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/public.py", line 958, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/public.py", line 4356, in __init__
    self._load()
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/public.py", line 5077, in _load
    raise ValueError(
ValueError: Project mlops-zoomcamp-wandb/jgammerman does not contain artifact: "NYC-Taxi:v0"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/mlops-zoomcamp/cohorts/2023/02-experiment-tracking/homework-wandb/train.py", line 63, in <module>
    run_train()
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mlops-zoomcamp/cohorts/2023/02-experiment-tracking/homework-wandb/train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2676, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/public.py", line 958, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/public.py", line 4356, in __init__
    self._load()
  File "/home/ubuntu/anaconda3/envs/WandB/lib/python3.11/site-packages/wandb/apis/public.py", line 5077, in _load
    raise ValueError(
wandb.errors.CommError: Project mlops-zoomcamp-wandb/jgammerman does not contain artifact: "NYC-Taxi:v0"